### ISSUE TITLE
Web NFC4PC

### ISSUE THREAD

**Issue by cyberphone** [martinpaljak/nfc4pc#5]
https://github.com/cyberphone/qr-replacement

Just F.Y.I.

Seems to not happen :(

**Comment by martinpaljak** [comment]
Thanks!

What you describe I think these days passkeys with the qr based “use a key on a phone” is supposed to be similar. I wish the protocol also allowed to use nfc tokens via the internal “complete on phone with qr” flow…

**Comment by martinpaljak** [comment]
Closing as FYI/non-actionable
